### ISSUE TITLE
Trying to use with a google form only says multiple cells updated

### ISSUE THREAD

**Issue by AustinTheSleepy** [Kelo/Google-Sheets-to-Discord#1]
I was hoping to have it read off one specific cell in a column each time a new post is updated? for example if someone fills out a google form, it would just show their name. Is this possible?

**Comment by Kelo** [comment]
Hi there, yep that's possible but you're using the wrong repo!
To get form responses in the way you're wanting I'd recommend using the google forms to discord extended repo. In that you can setup an if statement to stop the data from appending to the embed.

**Comment by AustinTheSleepy** [comment]
Thank you! However, I was looking at it as having only specific responses come in as webhooks. I have people who get a passing score be put on a diff sheet (where the script is rn). That’s why I used the sheet instead of the form, but if there’s a way to only post limited scores too on forms, I’d love to get help on that too! Thank you.

**Comment by Kelo** [comment]
You can setup and if statement to check the score and only send the webhook if the score is above/below a certain value.

**Comment by AustinTheSleepy** [comment]
Does this fit for sheets or google form?

**Comment by Kelo** [comment]
For what you're wanting to do I'd recommend the other repo - forms
