### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Progefix** [Kelo/Google-Sheets-to-Discord#2]
hi there :)

when is start the script i become that error

`TypeError: Cannot read property 'range' of undefined onEdit @ main.gs:4`

how can i fix that?

**Comment by Kelo** [comment]
Have you made any edits to the code? If so what are they. 

Did you setup the event trigger on the spreadsheet for this? The error would really only occur if you're testing it by clicking run and not binding it to an event trigger and making an edit on your sheet.

**Comment by Progefix** [comment]
No i dont change something. i added the webhook and the trigger is added. how can i add it to my sheet?

**Comment by Kelo** [comment]
You can add it to your sheet by opening the script editor after opening your sheet. 

To test that it's working fine, you should make an edit on your spreadsheet
