### ISSUE TITLE
How to only trigger when changing a certain column 

### ISSUE THREAD

**Issue by sinaeh10** [Kelo/Google-Sheets-to-Discord#3]
Hi there, thank you so much for this script :)

I am trying to make it so that changes in only a certain column ("C" or the third column on my spreadsheet) triggers a message on Discord.

I added your code after ```var items = [];```

```
  // If you only want to watch a certain column
  var column_id = 3
  // If not the column you want to watch
  if (column_id < event.range.getColumn() || column_id > event.range.getLastColumn ){
      // Do nothing
      return;
  }
```

However, it still is triggered to send a message if I change any cell on the spreadsheet, not just the third column. How do I specify that I only want the third column to be triggered?  I tried doing ```var column_id = "C"``` but it didn't recognize that as anything so I am probably misunderstanding how to do this xD

Thank you again!

**Comment by Kelo** [comment]
Hi @sinaeh10!

Thanks for the issue :)

Apologies for the bug, but I've missed some brackets!
The call `event.range.getLastColumn` should be `event.range.getLastColumn()` 

If the issue still persists, just let me know.

**Comment by sinaeh10** [comment]
That worked! Thank you so much!
