### ISSUE TITLE
Cannot read properties of 'undefined'

### ISSUE THREAD

**Issue by ongunumutyelbasi** [Kelo/Google-Sheets-to-Discord#6]
Hi, 
I've set up everything as instructed but I can't get the code to get triggered. The error I get is as below:

```
TypeError: Cannot read properties of undefined (reading 'range')
onEdit	@ EditNotif.gs:4
```

What am I doing wrong?
Thanks

**Comment by Kelo** [comment]
This sounds like you're not setting up the event correctly. Is the function using the parameter `event` ?

The function definition should look like:
```js
function onEdit(event){
```
