### ISSUE TITLE
This code works wonderfully, but I have a question about pasted data

### ISSUE THREAD

**Issue by Professor215** [Kelo/Google-Sheets-to-Discord#7]
Thank you so much for sharing this, it has helped me tremendously for the task I was trying to accomplish. It performs the purpose I need when the target column has manual edits to individual cells to notify on each cell change. 

But when I try to paste a full column worth of data, it is not triggering. Is there a way to get edit the code to allow for pasted data into the target cell or column range specificed?

**Comment by Kelo** [comment]
For pasted data, you'll have to use something like:
```js
if (event.range.rowStart != event.range.rowEnd || event.range.columnStart != event.range.columnEnd){
  reason = "Multiple cells copied in. Range: " + event.range.getA1Notation();
}

```
NB: I haven't tested this bit of code.


However, I would've suspected `"Multiple Cells edited"` to have been returned in the embed.

**Comment by Professor215** [comment]
From what I have found in testing, if I paste in data there is no return, and I suspect that the onEdit function is not firing for pasted data. 

Perhaps if you can test your original code, or with the addition you mentioned above, to see if you get any return. 

I suspect this is potentially a limitation of the onEdit function, where pasting data isn't triggering the function as it would if you typed the data into the cell. Perhaps there is an alteration needed to the onEdit... 

Would appreciate any testing on your side to confirm. Thank you again for your time. This really helped me a ton. 

I created a work around using AutoHotkey, where I copy a column then Send each line into the target column, thus "typing" in changes to each line to trigger the onEdit.
