### ISSUE TITLE
Edit range to?

### ISSUE THREAD

**Issue by LewisConnorx** [Kelo/Google-Sheets-to-Discord#8]
Hi,

I have no experience with code but I am trying to figure this out and have gotten stumped. I have completed all the steps needed but the execution log shows this:

![image](https://github.com/Kelo/Google-Sheets-to-Discord/assets/108419976/33e35fe2-3a47-449d-93c1-c94f6437b009)

I have seen I need to edit "range" but I'm unsure what this actually means, any help would be great!

**Comment by Kelo** [comment]
You don't need to edit a variable. 

By edit a range I mean edit a range of cells (e.g. A1:A2) or just a single cell to make sure the webhook works.

You shouldn't be running this via the run button. It can't be tested that way.
